port: 8080

postgres:
  user: "danyil" 
  # password: "postgres"
  dbname: "to-do"
  sslmode: "disable"
  host: "localhost"
  port: "5432"
auth:
  hash_salt: "hash_salt"
  signing_key: "signing_key"
  token_ttl: 43200